apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: staging
spec:
  encryptedData:
    password: AgBEzof8hr80xd7w70KJZgpjB/A3n5h3zgMWtAvjXrDP9qjEbR/6OERNqvLFHAayHSqFEDiMyjsXUqLqL09dORZDYkUHnpCCoQKJ91VT0TmRvZrG1es4WO/1rBH0zdUOi+sZ0COWU2lHpiKWxCVqGaHj1Ouv1XrnuHBPpkgjP+MlnwobD9g1Xhv3NcAku+GbZnecmGtUvQM9tZ2ql3rZzNWCnLbxz+OHDeYBANDX+vz9trTHewEBo6NvRgFtrsnTszA8rJBTb/46FAti9NUA2GjOFUYKw920BfnLN6xY2oZ/ND1rmbeaZysvJJhOsmOuuG5nhu4r41TLSq8OTb0nvEhzpuUdnFiz8bqgvQQaZogi4/5+HtFpLzRGFuKMbYlB6iLXa2Pvc6ap1iJ8F0OIlAkBmwjdssMSqoVNwayUQa3vx/8NFuGYL48DvcQfNT2bCCOv7R5g7n1jjvypOkHzfpgkGbC8DCI7vtCWXLG4jvVEwp0V/EhVoclL0on1lYU494IWdQb+iee5ilXOI9l2XQeA1POD19dYpe5KE5+TtobmBQpzCdiJ8trmerUa6z7dvPaXYEzbvp27eiVRCX23PVBaTCG4aWlm9Hm6EuwGEAkXv8MZNPmKeQkSLGGuyQ5pOD2K0NdB8OGy0cNKWRWQnlfgC+ctwfTasihaV+JvLnDnkG6WNusC/XKO7YNeDiyKCdMMflQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: staging

