apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: production
spec:
  encryptedData:
    password: AgAn/Ad3hODDgw4m6xVemdSOsE0rMSUnSxCiGkkHq7aXrRFWHdZTLp6rdjo0PEmvdoOnAmpJb4ay/vD3mRPdW3hNpW1HvZfFKqMGqYuBUUBNYBKIv508RGly5rhpqdluC22yTdDYGqeQKSlRCz9SIyZ2gnDc4Jxuw2/UaHNNzMHmUuFkHjk+VAjymEMevhjf3YZbVuG10ykx8qqs5xs7FPWaUbxG0FF3jm6CMrDl4fW3F3WCj+u3/93hXPR5h+psdMFLBdCSKXen9HxBHFcm0KSb83TPTY+AR97TNHvnAIXHOzoe1kn4tTcWZEf27p/3fgwbzLPsIpUu35/gfAUbcdArA/qion8sLf2Bp5Kz+iiUYx/0nBcap1KMmAjlb6UCIgv+qjcG50jjgU3XzZ+XE1izs4Rp8N7L4kfjXW8Bc3RAz22zRxWRcZyczGkZvnxZ8l5XRr+HAF7MZhNB6vPU/QoC/OYlYd3UP5APA7S9QwZyv29oCQuVCfeuzFs2hhLCvcaq6cvN+zQSd7MYcABIxyUjPZByqELIR12Wctt+JbwYHnBAW/Mda7i/s1abWP6JBrJjB9mOPj0/2RyTIzwoLDCCaA8Acz6CYqSpH5ck/TTsP+JI+jrtc+/lbr5WeQ3cH2bVlNlZoDGPPJ4YnS3RQg24u2lzgcX5fU7UEou6MV/RNRPHxiAXQca8h+2HfhfBvXkhuN5mJJk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: production

