apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-example-app-development
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: gitops-example-app=marklechtermann/gitops-example-app
    argocd-image-updater.argoproj.io/gitops-example-app.update-strategy: latest
    argocd-image-updater.argoproj.io/gitops-example-app.allow-tags: regexp:^[0-9]?\.[0-9]?\.2-dev\.*$    
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/overlays/development
    repoURL: https://github.com/marklechtermann/gitops-example-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
