apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-example-app-production
  namespace: argocd
  annotations:
    #argocd-image-updater.argoproj.io/image-list: marklechtermann/gitops-example-app:0.x
    #argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/overlays/production
    repoURL: https://github.com/marklechtermann/gitops-example-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
