apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-example-app-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/my-app-service.update-strategy: semver
    argocd-image-updater.argoproj.io/image-list: my-app-service=marklechtermann/gitops-example-app:1.x
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/overlays/staging
    repoURL: https://github.com/marklechtermann/gitops-example-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
