apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

patchesJson6902:
  - target:
      version: v1
      kind: Ingress
      name: gitops-example
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "production.127.0.0.1.nip.io"
