apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: development
spec:
  encryptedData:
    password: AgAEh5v6/fNMyz/oSA1X+x5lGP+w4ShD+gj2dQXUBsvWvG9Vldhiie1otmu/oURk627q1tiDmrUqMc3EMhUjcPTWKGsXc0Eyh8RWk77NrtVc56Jg56/GCDrSRrIVFvME3L2BjL9Q/bUtX7XWTa14LGwDZMvsBj+WZ6uShWnfLeq2XlDCFh9wReBr5hTfqBuVvgTQXtoiOGuGQnTP+oSH7wWvEMCamnjuKgerd6+mCL7/2SB4WL4NI8i3VKkR0fLK0gy10nd93ZY3bw+SyH6o8Ifj/EtKxMbWXVNjfnL2fSni7JfIyfng7gk85eCAHzZjjIJ+tthdJq4/SyNhF9MrGn7zfWJCfx+2HRJEXz/x7P5JAT7o5VvJOcLZwBQeZF+hRk2w432IC6i0lBWRgnNJlMtcs9Y/4iLXTx6mMVCQN1I30xiWN+EeyXbD/9vI0jiRb3ZCCgbhs/jyeHVZ3C4k9bRm+uZlFBb3TCNxAi1xRUoD7LkXvJ+24Hc39BpKF1yqEP8QgGlOhkGjK16/NKUARhxX3I1h79ecldDdmkajFttEx/29z7oTlSXgngKzcGeDo2c4quFpZjt3pKlKP/+2vReewapNOacsb4Luf9NaUr3cTXuiV9oBK0F5/62/mxbkMnohxXUfX9xyF6Ya5GG1PzyL0mHJnKqFen6kckcccjkYdcMRRpyHRMYzFrSJjI2GVE8SjNpINTW6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: development

